name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.7.1
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.0.8
  device_info_plus: '>=8.0.0 <10.0.0'
  device_info_plus_platform_interface: ^7.0.0
  package_info_plus: 4.0.2
  mailer: ^6.0.0
  dio: ^5.0.0
  flutter_mailer: ^2.0.0
  logging: ^1.0.2
  sentry: ^7.0.0
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
